name: Build and Release

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main  # You can adjust this to other branches if necessary

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment using the version specified in package.json
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install project dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run prebuild script (if any)
      - name: Run prebuild script
        run: npm run prebuild

      # Step 5: Build the project
      - name: Build the project
        run: npm run build

      # Step 6: Create a new Git tag
      - name: Create Git Tag
        run: |
          TAG_NAME="v$(date +'%Y%m%d%H%M%S')"  # Generate tag based on timestamp
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV  # Store tag name in environment
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git tag $TAG_NAME
          git push origin $TAG_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 7: Create a GitHub release using the new tag
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
